### ISSUE TITLE
Compilation error while linking the vgfont library

### ISSUE THREAD

**Issue by xeonqq** [tasanakorn/rpi-mmal-demo#1]
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/mydem/rpi-mmal-demo/build
Scanning dependencies of target mmal_buffer_demo
[ 25%] Building C object CMakeFiles/mmal_buffer_demo.dir/buffer_demo.c.o
Linking C executable mmal_buffer_demo
[ 25%] Built target mmal_buffer_demo
Scanning dependencies of target mmal_opencv_demo
[ 50%] Building C object CMakeFiles/mmal_opencv_demo.dir/opencv_demo.c.o
Linking C executable mmal_opencv_demo
/usr/bin/ld: cannot find -lvgfont
collect2: ld returned 1 exit status
make[2]: **\* [mmal_opencv_demo] Error 1
make[1]: **\* [CMakeFiles/mmal_opencv_demo.dir/all] Error 2
make: **\* [all] Error 2

**Comment by ahmedbk** [comment]
hi everyone ! when i tested i had these built targets and i tried them but i didnt get the face detection ! i had juste the camera opened and everytime it is blocked so i had to kill the process ! any help please ?
root@raspberrypi:~/Desktop/rpi-mmal-demo-develop# make
[ 20%] Built target mmal_buffer_demo
[ 40%] Built target mmal_opencv_demo
[ 60%] Built target mmal_opencv_window_demo
[ 80%] Built target mmal_video_record
[100%] Built target mmaldemo
